# Generated by Django 5.2.4 on 2025-07-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BirthRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_id",
                    models.CharField(
                        help_text="e.g., BREG/2024/0001", max_length=30, unique=True
                    ),
                ),
                ("child_first_name", models.CharField(max_length=100)),
                ("child_last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "place_of_birth",
                    models.CharField(
                        help_text="Hospital, Clinic, Home Address, etc.", max_length=200
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "father_full_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("mother_full_name", models.CharField(max_length=200)),
                ("registration_date", models.DateField(auto_now_add=True)),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True,
                        help_text="Official certificate number, if issued",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Birth Registration",
                "verbose_name_plural": "Birth Registrations",
                "ordering": [
                    "-registration_date",
                    "child_last_name",
                    "child_first_name",
                ],
            },
        ),
        migrations.CreateModel(
            name="DeathRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_id",
                    models.CharField(
                        help_text="e.g., DREG/2024/0001", max_length=30, unique=True
                    ),
                ),
                ("deceased_first_name", models.CharField(max_length=100)),
                ("deceased_last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("date_of_death", models.DateField()),
                (
                    "place_of_death",
                    models.CharField(
                        help_text="Hospital, Clinic, Home Address, etc.", max_length=200
                    ),
                ),
                (
                    "age_at_death_years",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Calculated or provided age in years",
                        null=True,
                    ),
                ),
                (
                    "cause_of_death",
                    models.CharField(
                        blank=True, help_text="Primary cause of death", max_length=255
                    ),
                ),
                ("registration_date", models.DateField(auto_now_add=True)),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True,
                        help_text="Official certificate number, if issued",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Death Registration",
                "verbose_name_plural": "Death Registrations",
                "ordering": [
                    "-registration_date",
                    "deceased_last_name",
                    "deceased_first_name",
                ],
            },
        ),
    ]
