# Generated by Django 5.2.4 on 2025-07-08 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr_payroll", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevenueSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Property Rate, Business Permit, Market Toll",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RevenueCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_collected", models.DateField()),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True,
                        help_text="Optional unique receipt number",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "collected_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employee who collected the revenue",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr_payroll.employee",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="The source of this revenue",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collections",
                        to="finance.revenuesource",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_collected", "-id"],
            },
        ),
    ]
