# Generated by Django 5.2.4 on 2025-07-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PermitApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_id",
                    models.CharField(
                        help_text="Unique ID for the application, e.g., BA/2024/0001",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "applicant_name",
                    models.CharField(
                        help_text="Full name of the individual or company applying",
                        max_length=200,
                    ),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("BUILDING", "Building Permit"),
                            ("LAND_USE", "Land Use Change"),
                            ("ZONING", "Zoning Request"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("application_date", models.DateField(auto_now_add=True)),
                ("last_updated_date", models.DateField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("INSPECTION_SCHEDULED", "Inspection Scheduled"),
                            ("AWAITING_PAYMENT", "Awaiting Payment"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="SUBMITTED",
                        max_length=30,
                    ),
                ),
                (
                    "property_location_details",
                    models.TextField(
                        help_text="Detailed address or plot number and location of the property"
                    ),
                ),
            ],
            options={
                "ordering": ["-application_date", "applicant_name"],
            },
        ),
    ]
